<?php /** @var \Snowdog\DevTest\Controller\VarnishesAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Varnishes - Cache Warmer</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">

    <script type = "text/javascript" 
         src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
      </script>
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div class="container">

    <?php if (isset($_SESSION['flash'])): ?>
        <p class="bg-info"><?= $_SESSION['flash'] ?></p>
        <?php unset($_SESSION['flash']) ?>
    <?php endif ?>

    <div>

        <div class="padded">
            <form id="xmlForm" action="sitemap" method="post" enctype="multipart/form-data">
                <input id="upload_file" name="the_file" type="file"> 
                <input type="submit" name="submit" value="Start Upload( csv )">
            </form>
            <h4>Or you can use this</h4>
            <div id="superhero-group" class="form-group">
                <label for="superheroAlias">Sitemap Url</label>
                <input
                    type="text"
                    class="form-control"
                    id="sitemap_url"
                    name="sitemap_url"
                    placeholder="Sitemap Url"
                />
                <button id="submit_url">Submit URL</button>
            </div>
            
            <script>
                jQuery('#submit_url').click(function(event) {
                    var curlurl = jQuery('#sitemap_url').val();
                    jQuery("button#submit_url").prop('disabled', true);
                        jQuery.ajax({
                            type: "POST",
                            url: "sitemapcurl",
                            data: {sitemapurl:curlurl},
                            dataType: "json",
                            success          :   function( data ) {
                                if( data.success ){
                                    alert('Sync url successfully');
                                }else{
                                    alert(data.message);
                                }
                            },
                            complete        :   function() {
                                jQuery("button#submit_url").prop('disabled', false);
                            }
                        });
                });
            </script>
        </div>

        <div class="padded">
            <h1>Sitemap Assignments</h1>
        </div>


    </div>

</div><!-- /.container -->


</body>
</html>